[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step required for backend'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"